%% BXDRONE: MATLAB CODE
%  Get data from the text files generated by the Java program
%  and plot the results

clear
clc

% Open data files
timeFileID = fopen('../Java/timeData.txt');
anglesFileID = fopen('../Java/anglesData.txt');
accelFileID = fopen('../Java/accelData.txt');
gyroFileID = fopen('../Java/gyroData.txt');
mSpeedFileID = fopen('../Java/mSpeedData.txt');
mDiffFileID = fopen('../Java/mDiffData.txt');

% Read data files content
time = textscan(timeFileID, '%d');
angles = textscan(anglesFileID, 'PITCH:%f32 ROLL:%f32');
accel = textscan(accelFileID, 'X:%f Y:%f Z:%f');
gyro = textscan(gyroFileID, 'X:%f Y:%f Z:%f');
mSpeed = textscan(mSpeedFileID, 'M1:%d M2:%d M3:%d M4:%d');
mDiff = textscan(mDiffFileID, 'M1_DIFF:%f M2_DIFF:%f M3_DIFF:%f M4_DIFF:%f');

% Close files
fclose(timeFileID);
fclose(anglesFileID);
fclose(mSpeedFileID);
fclose(accelFileID);
fclose(mDiffFileID);

% Plot results
% Plot pitch and roll
figure(1)
subplot(2,1,1)
plot(time{1},angles{1})
title('Pitch')
subplot(2,1,2)
plot(time{1},angles{2})

% Plot accelerometer data
figure(2)
subplot(3,1,1)
plot(time{1},accel{1})
title('X Accel')
subplot(3,1,2)
plot(time{1},accel{2})
title('Y Accel')
subplot(3,1,3)
plot(time{1},accel{3})
title('Z Accel')

% Plot gyroscope data
figure(3)
subplot(3,1,1)
plot(time{1},gyro{1})
title('X Gyro')
subplot(3,1,2)
plot(time{1},gyro{2})
title('Y Gyro')
subplot(3,1,3)
plot(time{1},gyro{3})
title('Z Gyro')

% Plot Motors speed data
figure(4)
plot(time{1},mSpeed{1},time{1},mSpeed{2},time{1},mSpeed{3},time{1},mSpeed{4})
title('Motors speed');
legend('Motor 1', 'Motor 2', 'Motor 3', 'Motor 4');

% Plot Motors PID speed component data
figure(5)
plot(time{1},mDiff{1},time{1},mDiff{2},time{1},mDiff{3},time{1},mDiff{4})
title('Motors speed: PID component');
legend('Motor 1', 'Motor 2', 'Motor 3', 'Motor 4');