import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.text.BadLocationException;
import java.awt.event.MouseEvent;

public class GraphicInterface extends JFrame{
    
	/* serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/* Number of lines to be displayed in the Data panel */
	private static final long InputOutputData_nLines = 200;
	
	/* Flag that determines if we are capturing InOut data */
	private static boolean dataCaptionOn = true;
	
	/* Lock for InOut data visualization */
	private Lock InOutDataLock = new ReentrantLock();
    
	/* PID parameters */
	private int [][]PIDKv = new int[6][3];
	
	/* GUI components */
    private JTextArea textAreaCommand;
    private JButton btnConnect;
    private JPanel panelMotors;
    private JProgressBar barTime3;
    private JProgressBar barTime2;
    private JProgressBar barTime1;
    private JProgressBar barTime4;
    private JProgressBar barTime5;
    private JProgressBar barTime6;
    private JProgressBar barTime7;
    private JLabel elblTime;
    private JButton btnStartRec;
    private JLabel elblRecStatus;
    private final ButtonGroup btngrpData = new ButtonGroup();
    private JTextArea textAreaInputData;
    private JTextArea textAreaOutputData;
    private JLabel lblDataCaption;
    private JSlider sliderDataCaption;
    private JRadioButton rdbtnHexData;
    private JRadioButton rdbtnBinaryData;
    private JLabel elblTimeLabel1;
    private JLabel elblTimeLabel2;
    private JLabel elblTimeLabel3;
    private JLabel elblTimeLabel6;
    private JLabel elblTimeLabel5;
    private JLabel elblTimeLabel4;
    private JLabel elblTimeLabel7;
    private final ButtonGroup btngrpPID = new ButtonGroup();
    private JProgressBar barM4PIDSpeed;
    private JProgressBar barM3PIDSpeed;
    private JProgressBar barM2PIDSpeed;
    private JProgressBar barM1PIDSpeed;
    private JProgressBar barM4UserSpeed;
    private JProgressBar barM3UserSpeed;
    private JProgressBar barM2UserSpeed;
    private JProgressBar barM1UserSpeed;
    private JRadioButton rdbtnP;
    private JRadioButton rdbtnI;
    private JRadioButton rdbtnD;
    private JSlider sliderPR;
    private JSlider sliderRR;
    private JSlider sliderYR;
    private JSlider sliderPS;
    private JSlider sliderRS;
    private JSlider sliderYS;
    private JLabel elblPR;
    private JLabel elblRR;
    private JLabel elblYR;
    private JLabel elblPS;
    private JLabel elblRS;
    private JLabel elblYS;
    private JButton btnTestMotors;
    private JButton btnPIDSwitch;
    private JLabel elblPIDSwitch;
    private JProgressBar barRoll;
    private JProgressBar barYaw;
    private JProgressBar barGyroZ;
    private JProgressBar barGyroY;
    private JProgressBar barGyroX;
    private JProgressBar barPitch;
    private JButton btnM2Switch;
    private JButton btnM1Switch;
    private JButton btnM4Switch;
    private JButton btnM3Switch;
    private DefaultComboBoxModel<String> boxCOMModel = new DefaultComboBoxModel<String>();
    private DefaultComboBoxModel<String> boxControllerCOMModel = new DefaultComboBoxModel<String>();
    private JComboBox<String> boxCOMPort;
    private JComboBox<String> boxControllerCOMPort;

    
    /*
     * Constructor. Generated by WindowBuilder
     */
    public GraphicInterface(){
        super("BXDrone");
        setResizable(false);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1100, 600));        
        pack();
        getContentPane().setLayout(null);
        
        JLabel lblHeader = new JLabel("BXDRONE");
        lblHeader.setHorizontalAlignment(SwingConstants.CENTER);
        lblHeader.setFont(new Font("Tahoma", Font.PLAIN, 20));
        lblHeader.setBounds(85, 11, 100, 23);
        getContentPane().add(lblHeader);
        
        JPanel panelCommand = new JPanel();
        panelCommand.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Command Window", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelCommand.setBounds(14, 297, 306, 254);
        getContentPane().add(panelCommand);
        panelCommand.setLayout(null);
        
        JScrollPane scrollPaneCommand = new JScrollPane();
        scrollPaneCommand.setAutoscrolls(true);
        scrollPaneCommand.setBounds(6, 16, 290, 227);
        panelCommand.add(scrollPaneCommand);
        
        textAreaCommand = new JTextArea();
        textAreaCommand.setFont(new Font("Courier New", Font.PLAIN, 12));
        scrollPaneCommand.setViewportView(textAreaCommand);
        scrollPaneCommand.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        textAreaCommand.setLineWrap(true);
        textAreaCommand.setWrapStyleWord(true);
        textAreaCommand.setEditable(false);
        textAreaCommand.setMargin(new Insets(0,5,0,5));
        
        JPanel panelServer = new JPanel();
        panelServer.setBorder(new TitledBorder(null, "Server", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelServer.setBounds(14, 74, 306, 119);
        getContentPane().add(panelServer);
        panelServer.setLayout(null);
        
        btnConnect = new JButton("Connect");
        btnConnect.setBounds(207, 84, 89, 23);
        btnConnect.addActionListener(new ActionListener(){
        	public void actionPerformed(ActionEvent e){
        		Thread myThread = new Thread(){
        			public void run(){
        				btnConnect.setEnabled(false);
        				boxCOMPort.setEnabled(false);
        				MainAction.connect();
        			}
        		};
        		myThread.start();
        	}
        });
        panelServer.add(btnConnect);
        
        JLabel lblPort = new JLabel("Port:");
        lblPort.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblPort.setBounds(10, 20, 46, 14);
        panelServer.add(lblPort);
        
        boxCOMPort = new JComboBox<>(boxCOMModel);
        boxCOMPort.setBounds(152, 16, 144, 23);
        panelServer.add(boxCOMPort);
        
        boxControllerCOMPort = new JComboBox<String>(boxControllerCOMModel);
        boxControllerCOMPort.setBounds(152, 50, 144, 23);
        panelServer.add(boxControllerCOMPort);
        
        JLabel lblControllerPort = new JLabel("Controller:");
        lblControllerPort.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblControllerPort.setBounds(10, 54, 132, 14);
        panelServer.add(lblControllerPort);
        
        JPanel panelTMTC = new JPanel();
        panelTMTC.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "TM/TC", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelTMTC.setBounds(330, 11, 754, 548);
        getContentPane().add(panelTMTC);
        panelTMTC.setLayout(null);
        
        panelMotors = new JPanel();
        panelMotors.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Motors", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
        panelMotors.setBounds(10, 19, 428, 143);
        panelTMTC.add(panelMotors);
        panelMotors.setLayout(null);
        
        JLabel lblM1Speed = new JLabel("M1 Speed:");
        lblM1Speed.setBounds(10, 28, 104, 14);
        panelMotors.add(lblM1Speed);
        lblM1Speed.setFont(new Font("Courier New", Font.PLAIN, 14));
        
        barM1UserSpeed = new JProgressBar();
        barM1UserSpeed.setToolTipText("");
        barM1UserSpeed.setStringPainted(true);
        barM1UserSpeed.setString("0");
        barM1UserSpeed.setMaximum(1000);
        barM1UserSpeed.setForeground(new Color(255, 165, 0));
        barM1UserSpeed.setBounds(97, 28, 116, 14);
        panelMotors.add(barM1UserSpeed);
        
        JLabel lblM2Speed = new JLabel("M2 Speed:");
        lblM2Speed.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblM2Speed.setBounds(10, 47, 104, 14);
        panelMotors.add(lblM2Speed);
        
        barM2UserSpeed = new JProgressBar();
        barM2UserSpeed.setToolTipText("");
        barM2UserSpeed.setStringPainted(true);
        barM2UserSpeed.setString("0");
        barM2UserSpeed.setMaximum(1000);
        barM2UserSpeed.setForeground(new Color(255, 165, 0));
        barM2UserSpeed.setBounds(97, 47, 116, 14);
        panelMotors.add(barM2UserSpeed);
        
        JLabel lblM3Speed = new JLabel("M3 Speed:");
        lblM3Speed.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblM3Speed.setBounds(10, 66, 104, 14);
        panelMotors.add(lblM3Speed);
        
        barM3UserSpeed = new JProgressBar();
        barM3UserSpeed.setToolTipText("");
        barM3UserSpeed.setStringPainted(true);
        barM3UserSpeed.setString("0");
        barM3UserSpeed.setMaximum(1000);
        barM3UserSpeed.setForeground(new Color(255, 165, 0));
        barM3UserSpeed.setBounds(97, 66, 116, 14);
        panelMotors.add(barM3UserSpeed);
        
        JLabel lblM4Speed = new JLabel("M4 Speed:");
        lblM4Speed.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblM4Speed.setBounds(10, 85, 104, 14);
        panelMotors.add(lblM4Speed);
        
        barM4UserSpeed = new JProgressBar();
        barM4UserSpeed.setToolTipText("");
        barM4UserSpeed.setStringPainted(true);
        barM4UserSpeed.setString("0");
        barM4UserSpeed.setMaximum(1000);
        barM4UserSpeed.setForeground(new Color(255, 165, 0));
        barM4UserSpeed.setBounds(97, 85, 116, 14);
        panelMotors.add(barM4UserSpeed);
        
        barM1PIDSpeed = new JProgressBar();
        barM1PIDSpeed.setMinimum(-255);
        barM1PIDSpeed.setToolTipText("");
        barM1PIDSpeed.setStringPainted(true);
        barM1PIDSpeed.setString("0");
        barM1PIDSpeed.setMaximum(255);
        barM1PIDSpeed.setForeground(new Color(255, 165, 0));
        barM1PIDSpeed.setBounds(223, 28, 116, 14);
        panelMotors.add(barM1PIDSpeed);
        
        barM2PIDSpeed = new JProgressBar();
        barM2PIDSpeed.setMinimum(-255);
        barM2PIDSpeed.setToolTipText("");
        barM2PIDSpeed.setStringPainted(true);
        barM2PIDSpeed.setString("0");
        barM2PIDSpeed.setMaximum(255);
        barM2PIDSpeed.setForeground(new Color(255, 165, 0));
        barM2PIDSpeed.setBounds(223, 47, 116, 14);
        panelMotors.add(barM2PIDSpeed);
        
        barM3PIDSpeed = new JProgressBar();
        barM3PIDSpeed.setMinimum(-255);
        barM3PIDSpeed.setToolTipText("");
        barM3PIDSpeed.setStringPainted(true);
        barM3PIDSpeed.setString("0");
        barM3PIDSpeed.setMaximum(255);
        barM3PIDSpeed.setForeground(new Color(255, 165, 0));
        barM3PIDSpeed.setBounds(223, 66, 116, 14);
        panelMotors.add(barM3PIDSpeed);
        
        barM4PIDSpeed = new JProgressBar();
        barM4PIDSpeed.setMinimum(-255);
        barM4PIDSpeed.setToolTipText("");
        barM4PIDSpeed.setStringPainted(true);
        barM4PIDSpeed.setString("0");
        barM4PIDSpeed.setMaximum(255);
        barM4PIDSpeed.setForeground(new Color(255, 165, 0));
        barM4PIDSpeed.setBounds(223, 85, 116, 14);
        panelMotors.add(barM4PIDSpeed);
        
        btnTestMotors = new JButton("Test Motors");
        btnTestMotors.setFont(new Font("Tahoma", Font.PLAIN, 11));
        btnTestMotors.setBounds(10, 109, 129, 23);
        btnTestMotors.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent arg0) {
				MainAction.arduino.sendTestMotors();
			}
        });
        panelMotors.add(btnTestMotors);
        
        JLabel lblUserSpeed = new JLabel("User Speed");
        lblUserSpeed.setHorizontalAlignment(SwingConstants.CENTER);
        lblUserSpeed.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblUserSpeed.setBounds(97, 11, 116, 14);
        panelMotors.add(lblUserSpeed);
        
        JLabel lblPIDSpeed = new JLabel("PID Speed");
        lblPIDSpeed.setHorizontalAlignment(SwingConstants.CENTER);
        lblPIDSpeed.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblPIDSpeed.setBounds(223, 11, 116, 14);
        panelMotors.add(lblPIDSpeed);
        
        btnM3Switch = new JButton("M3");
        btnM3Switch.setForeground(new Color(34, 139, 34));
        btnM3Switch.setBounds(287, 108, 59, 23);
        btnM3Switch.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				MainAction.arduino.sendMotorSwitch((short) 2);	
			}
        });
        panelMotors.add(btnM3Switch);
        
        btnM2Switch = new JButton("M2");
        btnM2Switch.setForeground(new Color(34, 139, 34));
        btnM2Switch.setBounds(218, 109, 59, 23);
        btnM2Switch.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				MainAction.arduino.sendMotorSwitch((short) 1);	
			}
        });
        panelMotors.add(btnM2Switch);
        
        btnM1Switch = new JButton("M1");
        btnM1Switch.setForeground(new Color(34, 139, 34));
        btnM1Switch.setBounds(149, 109, 59, 23);
        btnM1Switch.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				MainAction.arduino.sendMotorSwitch((short) 0);	
			}
        });
        panelMotors.add(btnM1Switch);
        
        btnM4Switch = new JButton("M4");
        btnM4Switch.setForeground(new Color(34, 139, 34));
        btnM4Switch.setBounds(356, 109, 59, 23);
        btnM4Switch.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				MainAction.arduino.sendMotorSwitch((short) 3);	
			}
        });
        panelMotors.add(btnM4Switch);
        
        JPanel panelTimeData = new JPanel();
        panelTimeData.setLayout(null);
        panelTimeData.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Time data", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelTimeData.setBounds(10, 308, 268, 170);
        panelTMTC.add(panelTimeData);
        
        JLabel lblTime = new JLabel("Time:");
        lblTime.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime.setBounds(10, 15, 58, 14);
        panelTimeData.add(lblTime);
        
        elblTime = new JLabel("0");
        elblTime.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTime.setBounds(53, 15, 68, 14);
        panelTimeData.add(elblTime);
        
        barTime1 = new JProgressBar();
        barTime1.setToolTipText("");
        barTime1.setForeground(new Color(255, 165, 0));
        barTime1.setString("0");
        barTime1.setStringPainted(true);
        barTime1.setMaximum(3000);
        barTime1.setBounds(142, 34, 116, 14);
        panelTimeData.add(barTime1);
        
        JLabel lblTime1 = new JLabel("Time 1:");
        lblTime1.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime1.setBounds(10, 34, 58, 14);
        panelTimeData.add(lblTime1);
        
        JLabel lblTime2 = new JLabel("Time 2:");
        lblTime2.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime2.setBounds(10, 53, 58, 14);
        panelTimeData.add(lblTime2);
        
        JLabel lblTime3 = new JLabel("Time 3:");
        lblTime3.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime3.setBounds(10, 72, 58, 14);
        panelTimeData.add(lblTime3);
        
        barTime2 = new JProgressBar();
        barTime2.setString("0");
        barTime2.setStringPainted(true);
        barTime2.setForeground(new Color(255, 165, 0));
        barTime2.setMaximum(3000);
        barTime2.setBounds(142, 53, 116, 14);
        panelTimeData.add(barTime2);
        
        barTime3 = new JProgressBar();
        barTime3.setForeground(new Color(255, 165, 0));
        barTime3.setStringPainted(true);
        barTime3.setString("0\r\n");
        barTime3.setMaximum(3000);
        barTime3.setBounds(142, 72, 116, 14);
        panelTimeData.add(barTime3);
        
        barTime4 = new JProgressBar();
        barTime4.setToolTipText("");
        barTime4.setStringPainted(true);
        barTime4.setString("0");
        barTime4.setMaximum(3000);
        barTime4.setForeground(new Color(255, 165, 0));
        barTime4.setBounds(142, 91, 116, 14);
        panelTimeData.add(barTime4);
        
        barTime5 = new JProgressBar();
        barTime5.setStringPainted(true);
        barTime5.setString("0");
        barTime5.setMaximum(3000);
        barTime5.setForeground(new Color(255, 165, 0));
        barTime5.setBounds(142, 110, 116, 14);
        panelTimeData.add(barTime5);
        
        barTime6 = new JProgressBar();
        barTime6.setStringPainted(true);
        barTime6.setString("0\r\n");
        barTime6.setMaximum(3000);
        barTime6.setForeground(new Color(255, 165, 0));
        barTime6.setBounds(142, 129, 116, 14);
        panelTimeData.add(barTime6);
        
        barTime7 = new JProgressBar();
        barTime7.setStringPainted(true);
        barTime7.setString("0\r\n");
        barTime7.setMaximum(3000);
        barTime7.setForeground(new Color(255, 165, 0));
        barTime7.setBounds(142, 148, 116, 14);
        panelTimeData.add(barTime7);
        
        JLabel lblTime5 = new JLabel("Time 5:");
        lblTime5.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime5.setBounds(10, 110, 58, 14);
        panelTimeData.add(lblTime5);
        
        JLabel lblTime6 = new JLabel("Time 6:");
        lblTime6.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime6.setBounds(10, 129, 58, 14);
        panelTimeData.add(lblTime6);
        
        JLabel lblTime7 = new JLabel("Time 7:");
        lblTime7.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime7.setBounds(10, 148, 58, 14);
        panelTimeData.add(lblTime7);
        
        JLabel lblTime4 = new JLabel("Time 4:");
        lblTime4.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblTime4.setBounds(10, 91, 58, 14);
        panelTimeData.add(lblTime4);
        
        elblTimeLabel1 = new JLabel();
        elblTimeLabel1.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel1.setBounds(67, 34, 65, 14);
        panelTimeData.add(elblTimeLabel1);
        
        elblTimeLabel2 = new JLabel();
        elblTimeLabel2.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel2.setBounds(67, 53, 65, 14);
        panelTimeData.add(elblTimeLabel2);
        
        elblTimeLabel3 = new JLabel();
        elblTimeLabel3.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel3.setBounds(67, 72, 65, 14);
        panelTimeData.add(elblTimeLabel3);
        
        elblTimeLabel6 = new JLabel();
        elblTimeLabel6.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel6.setBounds(67, 129, 65, 14);
        panelTimeData.add(elblTimeLabel6);
        
        elblTimeLabel5 = new JLabel();
        elblTimeLabel5.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel5.setBounds(67, 110, 65, 14);
        panelTimeData.add(elblTimeLabel5);
        
        elblTimeLabel4 = new JLabel();
        elblTimeLabel4.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel4.setBounds(67, 91, 65, 14);
        panelTimeData.add(elblTimeLabel4);
        
        elblTimeLabel7 = new JLabel();
        elblTimeLabel7.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblTimeLabel7.setBounds(67, 148, 65, 14);
        panelTimeData.add(elblTimeLabel7);
        
        JPanel panelRecData = new JPanel();
        panelRecData.setLayout(null);
        panelRecData.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Record data", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelRecData.setBounds(10, 477, 241, 60);
        panelTMTC.add(panelRecData);
        
        btnStartRec = new JButton("Start recording");
        btnStartRec.setFont(new Font("Tahoma", Font.PLAIN, 11));
        btnStartRec.setBounds(10, 22, 129, 23);
        btnStartRec.addActionListener(new ActionListener(){
        	public void actionPerformed(ActionEvent arg0){
        		if( !Telemetry.isRecordingData() ){
        			Telemetry.startRecordingData();
        			btnStartRec.setText("Stop recording");
        			elblRecStatus.setText("ON");
        			elblRecStatus.setForeground(Color.RED);
        		} else {
        			Telemetry.stopRecordingData();
        			btnStartRec.setText("Start recording");
        			elblRecStatus.setText("OFF");
        			elblRecStatus.setForeground(Color.BLACK);
        		}
        	}
        });
        panelRecData.add(btnStartRec);
        
        elblRecStatus = new JLabel("OFF");
        elblRecStatus.setHorizontalAlignment(SwingConstants.CENTER);
        elblRecStatus.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblRecStatus.setBounds(151, 26, 80, 14);
        panelRecData.add(elblRecStatus);
        
        JPanel panelData = new JPanel();
        panelData.setLayout(null);
        panelData.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Data", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
        panelData.setBounds(440, 19, 304, 518);
        panelTMTC.add(panelData);
        
        JScrollPane scrollPaneInputData = new JScrollPane();
        scrollPaneInputData.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneInputData.setAutoscrolls(true);
        scrollPaneInputData.setBounds(10, 58, 127, 412);
        panelData.add(scrollPaneInputData);
        
        textAreaInputData = new JTextArea();
        textAreaInputData.setLineWrap(true);
        textAreaInputData.setWrapStyleWord(true);
        scrollPaneInputData.setViewportView(textAreaInputData);
        textAreaInputData.setFont(new Font("Monospaced", Font.BOLD, 14));
        textAreaInputData.setForeground(Color.RED);
        textAreaInputData.setEditable(false);
        textAreaInputData.setBackground(Color.DARK_GRAY);
        
        JScrollPane scrollPaneOutputData = new JScrollPane();
        scrollPaneOutputData.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneOutputData.getVerticalScrollBar().setModel(scrollPaneInputData.getVerticalScrollBar().getModel());
        scrollPaneOutputData.setAutoscrolls(true);
        scrollPaneOutputData.setBounds(167, 58, 127, 412);
        panelData.add(scrollPaneOutputData);
        
        textAreaOutputData = new JTextArea();
        scrollPaneOutputData.setViewportView(textAreaOutputData);
        textAreaOutputData.setForeground(Color.GREEN);
        textAreaOutputData.setFont(new Font("Monospaced", Font.BOLD, 14));
        textAreaOutputData.setEditable(false);
        textAreaOutputData.setBackground(Color.DARK_GRAY);
        
        JLabel lblInputData = new JLabel("INPUT DATA");
        lblInputData.setHorizontalAlignment(SwingConstants.CENTER);
        lblInputData.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblInputData.setBounds(10, 33, 127, 14);
        panelData.add(lblInputData);
        
        JLabel lblOutputData = new JLabel("OUTPUT DATA");
        lblOutputData.setHorizontalAlignment(SwingConstants.CENTER);
        lblOutputData.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblOutputData.setBounds(167, 33, 127, 14);
        panelData.add(lblOutputData);
        
        rdbtnHexData = new JRadioButton("Hex");
        rdbtnHexData.setSelected(true);
        btngrpData.add(rdbtnHexData);
        rdbtnHexData.setBounds(10, 488, 51, 23);
        panelData.add(rdbtnHexData);
        
        rdbtnBinaryData = new JRadioButton("Bin");
        btngrpData.add(rdbtnBinaryData);
        rdbtnBinaryData.setBounds(62, 488, 58, 23);
        panelData.add(rdbtnBinaryData);
        
        sliderDataCaption = new JSlider();
        sliderDataCaption.setMaximum(1);
        sliderDataCaption.setValue(1);
        sliderDataCaption.setBounds(167, 481, 64, 23);
        sliderDataCaption.addMouseListener(new MouseListener(){
        	
			@Override
			public void mouseClicked(java.awt.event.MouseEvent e) {}
			@Override
			public void mousePressed(java.awt.event.MouseEvent e) {}
			@Override
			public void mouseReleased(java.awt.event.MouseEvent e) {
				if( sliderDataCaption.getValue() == 1 ){
					dataCaptionOn = true;
					lblDataCaption.setText("ON");
					lblDataCaption.setForeground(Color.GREEN);
				} else {
					dataCaptionOn = false;
					lblDataCaption.setText("OFF");
					lblDataCaption.setForeground(Color.RED);
				}
			}
			@Override
			public void mouseEntered(java.awt.event.MouseEvent e) {}
			@Override
			public void mouseExited(java.awt.event.MouseEvent e) {}
        });
        panelData.add(sliderDataCaption);
        
        lblDataCaption = new JLabel("ON");
        lblDataCaption.setForeground(Color.GREEN);
        lblDataCaption.setBounds(236, 484, 58, 14);
        panelData.add(lblDataCaption);
        lblDataCaption.setFont(new Font("Courier New", Font.PLAIN, 14));
        
        JPanel panelPID = new JPanel();
        panelPID.setBorder(new TitledBorder(null, "PID", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panelPID.setBounds(10, 163, 428, 143);
        panelTMTC.add(panelPID);
        panelPID.setLayout(null);
        
        sliderPR = new JSlider();
        sliderPR.setMaximum(10000);
        sliderPR.setValue(0);
        sliderPR.setBounds(32, 48, 120, 24);
        sliderPR.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 0, param, sliderPR.getValue());
			}
        });
        panelPID.add(sliderPR);
        
        sliderRR = new JSlider();
        sliderRR.setMaximum(10000);
        sliderRR.setValue(0);
        sliderRR.setBounds(32, 78, 120, 24);
        sliderRR.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 1, param, sliderRR.getValue());
			}
        });
        panelPID.add(sliderRR);
        
        sliderYR = new JSlider();
        sliderYR.setMaximum(10000);
        sliderYR.setValue(0);
        sliderYR.setBounds(32, 108, 120, 24);
        sliderYR.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 2, param, sliderYR.getValue());
			}
        });
        panelPID.add(sliderYR);
        
        sliderPS = new JSlider();
        sliderPS.setMaximum(10000);
        sliderPS.setValue(0);
        sliderPS.setBounds(233, 48, 120, 24);
        sliderPS.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 3, param, sliderPS.getValue());
			}
        });
        panelPID.add(sliderPS);
        
        sliderRS = new JSlider();
        sliderRS.setMaximum(10000);
        sliderRS.setValue(0);
        sliderRS.setBounds(233, 78, 120, 24);
        sliderRS.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 4, param, sliderRS.getValue());
			}
        });
        panelPID.add(sliderRS);
        
        sliderYS = new JSlider();
        sliderYS.setMaximum(10000);
        sliderYS.setValue(0);
        sliderYS.setBounds(233, 108, 120, 24);
        sliderYS.addMouseListener(new MouseListener(){
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// Get selected parameter
				short param;
				if( rdbtnP.isSelected() ) param = 0;
				else if( rdbtnI.isSelected() ) param = 1;
				else param = 2;
				
				// Send PID parameter
				MainAction.arduino.sendPIDKv((short) 5, param, sliderYS.getValue());
			}
        });
        panelPID.add(sliderYS);
        
        JLabel lblPR = new JLabel("PR:");
        lblPR.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblPR.setBounds(10, 51, 36, 14);
        panelPID.add(lblPR);
        
        JLabel lblRR = new JLabel("RR:");
        lblRR.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblRR.setBounds(10, 81, 36, 14);
        panelPID.add(lblRR);
        
        JLabel lblYR = new JLabel("YR:");
        lblYR.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblYR.setBounds(10, 111, 36, 14);
        panelPID.add(lblYR);
        
        JLabel lblPS = new JLabel("PS:");
        lblPS.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblPS.setBounds(211, 51, 36, 14);
        panelPID.add(lblPS);
        
        JLabel lblRS = new JLabel("RS:");
        lblRS.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblRS.setBounds(211, 81, 36, 14);
        panelPID.add(lblRS);
        
        JLabel lblYS = new JLabel("YS:");
        lblYS.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblYS.setBounds(211, 111, 36, 14);
        panelPID.add(lblYS);
        
        elblPR = new JLabel("000.00");
        elblPR.setHorizontalAlignment(SwingConstants.LEFT);
        elblPR.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblPR.setBounds(152, 51, 56, 14);
        panelPID.add(elblPR);
        
        elblRR = new JLabel("000.00");
        elblRR.setHorizontalAlignment(SwingConstants.LEFT);
        elblRR.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblRR.setBounds(152, 81, 56, 14);
        panelPID.add(elblRR);
        
        elblYR = new JLabel("000.00");
        elblYR.setHorizontalAlignment(SwingConstants.LEFT);
        elblYR.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblYR.setBounds(152, 111, 56, 14);
        panelPID.add(elblYR);
        
        elblPS = new JLabel("000.00");
        elblPS.setHorizontalAlignment(SwingConstants.LEFT);
        elblPS.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblPS.setBounds(354, 51, 56, 14);
        panelPID.add(elblPS);
        
        elblRS = new JLabel("000.00");
        elblRS.setHorizontalAlignment(SwingConstants.LEFT);
        elblRS.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblRS.setBounds(354, 81, 56, 14);
        panelPID.add(elblRS);
        
        elblYS = new JLabel("000.00");
        elblYS.setHorizontalAlignment(SwingConstants.LEFT);
        elblYS.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblYS.setBounds(354, 111, 56, 14);
        panelPID.add(elblYS);
        
        rdbtnP = new JRadioButton("P");
        rdbtnP.setSelected(true);
        btngrpPID.add(rdbtnP);
        rdbtnP.setBounds(6, 18, 56, 23);
        rdbtnP.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				updatePIDKvGUI();
			}
        });
        panelPID.add(rdbtnP);
        
        rdbtnI = new JRadioButton("I");
        btngrpPID.add(rdbtnI);
        rdbtnI.setBounds(66, 18, 56, 23);
        rdbtnI.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				updatePIDKvGUI();
			}
        });
        panelPID.add(rdbtnI);
        
        rdbtnD = new JRadioButton("D");
        btngrpPID.add(rdbtnD);
        rdbtnD.setBounds(128, 18, 56, 23);
        rdbtnD.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				updatePIDKvGUI();
			}
        });
        panelPID.add(rdbtnD);
        
        btnPIDSwitch = new JButton("PID Switch");
        btnPIDSwitch.setFont(new Font("Tahoma", Font.PLAIN, 11));
        btnPIDSwitch.setBounds(246, 18, 94, 23);
        btnPIDSwitch.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				MainAction.arduino.sendPIDSwitch();
			}
        });
        panelPID.add(btnPIDSwitch);
        
        elblPIDSwitch = new JLabel("OFF");
        elblPIDSwitch.setForeground(Color.RED);
        elblPIDSwitch.setFont(new Font("Courier New", Font.PLAIN, 14));
        elblPIDSwitch.setBounds(362, 22, 36, 14);
        panelPID.add(elblPIDSwitch);
        
        JPanel panel = new JPanel();
        panel.setBorder(new TitledBorder(null, "Angles / Gyro", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        panel.setBounds(279, 308, 159, 170);
        panelTMTC.add(panel);
        panel.setLayout(null);
        
        barPitch = new JProgressBar();
        barPitch.setToolTipText("");
        barPitch.setStringPainted(true);
        barPitch.setString("0");
        barPitch.setMinimum(-9000);
        barPitch.setMaximum(9000);
        barPitch.setForeground(new Color(255, 165, 0));
        barPitch.setBounds(33, 30, 116, 14);
        panel.add(barPitch);
        
        barRoll = new JProgressBar();
        barRoll.setToolTipText("");
        barRoll.setStringPainted(true);
        barRoll.setString("0");
        barRoll.setMinimum(-9000);
        barRoll.setMaximum(9000);
        barRoll.setForeground(new Color(255, 165, 0));
        barRoll.setBounds(33, 49, 116, 14);
        panel.add(barRoll);
        
        barYaw = new JProgressBar();
        barYaw.setStringPainted(true);
        barYaw.setToolTipText("");
        barYaw.setString("0");
        barYaw.setMinimum(-9000);
        barYaw.setMaximum(9000);
        barYaw.setForeground(new Color(255, 165, 0));
        barYaw.setBounds(33, 68, 116, 14);
        panel.add(barYaw);
        
        barGyroZ = new JProgressBar();
        barGyroZ.setToolTipText("");
        barGyroZ.setStringPainted(true);
        barGyroZ.setString("0");
        barGyroZ.setMinimum(-255);
        barGyroZ.setMaximum(255);
        barGyroZ.setForeground(new Color(255, 165, 0));
        barGyroZ.setBounds(33, 145, 116, 14);
        panel.add(barGyroZ);
        
        barGyroY = new JProgressBar();
        barGyroY.setToolTipText("");
        barGyroY.setStringPainted(true);
        barGyroY.setString("0");
        barGyroY.setMinimum(-255);
        barGyroY.setMaximum(255);
        barGyroY.setForeground(new Color(255, 165, 0));
        barGyroY.setBounds(33, 126, 116, 14);
        panel.add(barGyroY);
        
        barGyroX = new JProgressBar();
        barGyroX.setToolTipText("");
        barGyroX.setStringPainted(true);
        barGyroX.setString("0");
        barGyroX.setMinimum(-255);
        barGyroX.setMaximum(255);
        barGyroX.setForeground(new Color(255, 165, 0));
        barGyroX.setBounds(33, 107, 116, 14);
        panel.add(barGyroX);
        
        JLabel lblGyroX = new JLabel("GX:");
        lblGyroX.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblGyroX.setBounds(7, 107, 36, 14);
        panel.add(lblGyroX);
        
        JLabel lblGyroY = new JLabel("GY:");
        lblGyroY.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblGyroY.setBounds(7, 126, 36, 14);
        panel.add(lblGyroY);
        
        JLabel lblGyroZ = new JLabel("GZ:");
        lblGyroZ.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblGyroZ.setBounds(7, 145, 36, 14);
        panel.add(lblGyroZ);
        
        JLabel lblPitch = new JLabel("P:");
        lblPitch.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblPitch.setBounds(7, 30, 36, 14);
        panel.add(lblPitch);
        
        JLabel lblRoll = new JLabel("R:");
        lblRoll.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblRoll.setBounds(7, 49, 36, 14);
        panel.add(lblRoll);
        
        JLabel lblYaw = new JLabel("Y:");
        lblYaw.setFont(new Font("Courier New", Font.PLAIN, 14));
        lblYaw.setBounds(7, 68, 36, 14);
        panel.add(lblYaw);
        
        setVisible(true);
    }
    
    
    /*
     * Set initial window
     */
    public void setInitial(){
    	// Connection panel
    	btnConnect.setEnabled(true); 	
    	
    	// Motors panel
    	setMUserSpeed(new short[4]);
    	setMPIDSpeed(new short[4]);
    	btnTestMotors.setEnabled(false);
    	btnM1Switch.setEnabled(false);
    	btnM2Switch.setEnabled(false);
    	btnM3Switch.setEnabled(false);
    	btnM4Switch.setEnabled(false);
    	
    	// PID panel
    	sliderPR.setEnabled(false);
    	sliderRR.setEnabled(false);
    	sliderYR.setEnabled(false);
    	sliderPS.setEnabled(false);
    	sliderRS.setEnabled(false);
    	sliderYS.setEnabled(false);
    	elblPR.setText("N/A");
    	elblRR.setText("N/A");
    	elblYR.setText("N/A");
    	elblPS.setText("N/A");
    	elblRS.setText("N/A");
    	elblYS.setText("N/A");
    	btnPIDSwitch.setEnabled(false);
    	elblPIDSwitch.setForeground(Color.BLACK);
    	
    	// Time panel
    	elblTime.setText("N/A");
    	setTimeLabels(new String[7]);
    	setTimeBarValues(new long[8]);
    	
    	// Angles/Gyro panel
    	setYPR(new short[3]);
    	setGyroXYZ(new short[3]);
    	
    	// Record data panel
    	btnStartRec.setEnabled(false);
    	elblRecStatus.setText("OFF");
	}
    
    
    /*
     * Set connected window
     */
    public void setConnected(){
    	// Connection panel
    	btnConnect.setEnabled(false); 	
    	
    	// Motors panel
    	btnTestMotors.setEnabled(true);
    	btnM1Switch.setEnabled(true);
    	btnM2Switch.setEnabled(true);
    	btnM3Switch.setEnabled(true);
    	btnM4Switch.setEnabled(true);
    	
    	// PID panel
    	sliderPR.setEnabled(true);
    	sliderRR.setEnabled(true);
    	sliderYR.setEnabled(true);
    	sliderPS.setEnabled(true);
    	sliderRS.setEnabled(true);
    	sliderYS.setEnabled(true);
    	btnPIDSwitch.setEnabled(true);
    	
    	// Record data panel
    	btnStartRec.setEnabled(true);
    	
    	// Clear telemetry
    	clearTelemetry();    	
    	
    	// Request focus out of sliders and buttons
    	getContentPane().requestFocus(); 
    }
    
    public void print(String s){
    	textAreaCommand.append(s);
		textAreaCommand.setCaretPosition(textAreaCommand.getDocument().getLength());	
    }
    
    public void println(String s){
    	textAreaCommand.append(s);
    	textAreaCommand.append(Character.toString('\n'));
		textAreaCommand.setCaretPosition(textAreaCommand.getDocument().getLength());
    }
    
    
    /*
     * Clear all telemetry (set to 0)
     */
    public void clearTelemetry(){
    	// Motors TM
    	setMUserSpeed(new short[4]);
    	setMPIDSpeed(new short[4]);
    	
    	// PID TM
    	setPIDKv(new int[6][3]);
    	
    	// Time TM
    	setTimeBarValues(new long[8]);
    	
    	// Angles TM
    	setYPR(new short[3]);
    	
    	// Gyro TM
    	setGyroXYZ(new short[3]);
    }
    
    
    //**************************************************************//
    //******************** Motors TM Functions *********************//
    //**************************************************************//
    
    
    /*
     * Set motors user speed
     * 
     * @param mSpeed Array with the user speed of all 4 motors
     */
    public void setMUserSpeed(short[] mSpeed){
    	// Initial assert
    	if( mSpeed.length != 4 )
    		return;
    	
    	// Set bar values
    	barM1UserSpeed.setValue(mSpeed[0]);
    	barM2UserSpeed.setValue(mSpeed[1]);
    	barM3UserSpeed.setValue(mSpeed[2]);
    	barM4UserSpeed.setValue(mSpeed[3]);
    	
    	// Set bar labels
    	barM1UserSpeed.setString(Integer.toString(mSpeed[0]));
    	barM2UserSpeed.setString(Integer.toString(mSpeed[1]));
    	barM3UserSpeed.setString(Integer.toString(mSpeed[2]));
    	barM4UserSpeed.setString(Integer.toString(mSpeed[3]));
    }
    
    
    /*
     * Set motors PID speed
     * 
     * @param mSpeed Array with the PID speed of all 4 motors
     */
    public void setMPIDSpeed(short[] mSpeed){
    	// Initial assert
    	if( mSpeed.length != 4 )
    		return;
    	
    	// Set bar values
    	barM1PIDSpeed.setValue(mSpeed[0]);
    	barM2PIDSpeed.setValue(mSpeed[1]);
    	barM3PIDSpeed.setValue(mSpeed[2]);
    	barM4PIDSpeed.setValue(mSpeed[3]);
    	
    	// Set bar labels
    	barM1PIDSpeed.setString(Integer.toString(mSpeed[0]));
    	barM2PIDSpeed.setString(Integer.toString(mSpeed[1]));
    	barM3PIDSpeed.setString(Integer.toString(mSpeed[2]));
    	barM4PIDSpeed.setString(Integer.toString(mSpeed[3]));
    }
    
    
    /*
     * Enable / disable a motor
     * 
     * @param mSwitch Array containing the state of each motor
     */
    public void setMEnabled(int[] mSwitch){
    	// Initial assert
    	if( mSwitch.length != 4 )
    		return;
    	
    	// Initialize colors
    	Color[] color = new Color[4];
    	
    	// Select color of text
    	for( int i=0 ; i<4 ; i++ ){
	    	if( mSwitch[i] != 0 )
	    		color[i] = new Color(34, 139, 34);
	    	else
	    		color[i] = Color.RED;
    	}

    	// Set colors
		btnM1Switch.setForeground(color[0]);
		btnM2Switch.setForeground(color[1]);
		btnM3Switch.setForeground(color[2]);
		btnM4Switch.setForeground(color[3]);
    }
    
    
    //**************************************************************//
    //*********************** PID TM Functions *********************//
    //**************************************************************//    
    
    
    /*
     * Set PID parameters
     * 
     * param PID Two dimensional array including parameters of all PIDs
     */
    public void setPIDKv(int [][] PID){
    	// Initial assert
    	if( PID.length != 6 )
    		return;
    	
    	for( int i=0 ; i<6 ; i++ )
    		if( PID[i].length != 3 )
    			return;
    	
    	// Assign new PID parameters
    	PIDKv = PID;
    	
    	// Update GUI
    	updatePIDKvGUI();
    }
    
    
    /*
     * Updates which parameter we are visualizing
     */
    public void updatePIDKvGUI(){
    	// Get which parameter is visualized
    	int param;
    	if( rdbtnP.isSelected() ) param = 0;
    	else if( rdbtnI.isSelected() ) param = 1;
    	else param = 2;
    	
    	// Update GUI
    	NumberFormat formatter = new DecimalFormat("#0.00");
   		elblPR.setText(formatter.format(((double)PIDKv[0][param])/100));
   		elblRR.setText(formatter.format(((double)PIDKv[1][param])/100));
   		elblYR.setText(formatter.format(((double)PIDKv[2][param])/100));
   		elblPS.setText(formatter.format(((double)PIDKv[3][param])/100));
   		elblRS.setText(formatter.format(((double)PIDKv[4][param])/100));
   		elblYS.setText(formatter.format(((double)PIDKv[5][param])/100));
   		sliderPR.setValue(PIDKv[0][param]);
   		sliderRR.setValue(PIDKv[1][param]);
   		sliderYR.setValue(PIDKv[2][param]);
   		sliderPS.setValue(PIDKv[3][param]);
   		sliderRS.setValue(PIDKv[4][param]);
   		sliderYS.setValue(PIDKv[5][param]);    	
    }
    
    
    /*
     * Set PID enabled
     * 
     * @param en 1 if enabled. 0 otherwise.
     */
    public void setPIDEnabled(int en){
    	if( en == 1 ){
    		elblPIDSwitch.setText("ON");
    		elblPIDSwitch.setForeground(new Color(34, 139, 34));
    	} else {
    		elblPIDSwitch.setText("OFF");
    		elblPIDSwitch.setForeground(Color.RED);
    	}                                   
    }
    
    
    //************************************************************//
    //******************** Time TM Functions *********************//
    //************************************************************//
    
    
    /*
     * Set time labels
     * 
     * @param labels String array containing all the labels
     */
    public void setTimeLabels(String [] labels){
    	// Initial assert
    	if( labels.length > 7 ) 
    		return;
    	
    	String [] lb = new String[7];
    	
    	for( int i=0 ; i<labels.length ; i++ )
    		lb[i] = labels[i];
    	
    	elblTimeLabel1.setText(lb[0]);
    	elblTimeLabel2.setText(lb[1]);
    	elblTimeLabel3.setText(lb[2]);
    	elblTimeLabel4.setText(lb[3]);
    	elblTimeLabel5.setText(lb[4]);
    	elblTimeLabel6.setText(lb[5]);
    	elblTimeLabel7.setText(lb[6]);
    }
    
    
    /*
     * Set time values
     * 
     * @param timeRecs Array containing all time values
     */
    public void setTimeBarValues(long [] timeRecs){
    	
    	// Time label
    	long second = (timeRecs[0] / 1000) % 60;
		long minute = (timeRecs[0] / (1000 * 60));
    	elblTime.setText(String.format("%02d", minute) + ":" + String.format("%02d", second));
    	
    	// Check time variables length
    	int recsLength = timeRecs.length;
    	if(recsLength > 8) return;
    	
    	// Initialize colors and values for all bars
    	Color []clrs = new Color[7];
    	long []tms = new long[7];
    	
    	// Get color/value for bars
    	for( int i=0 ; i<recsLength-1 ; i++ ){
    		if( timeRecs[i+1] <= 1000 )
    			clrs[i] = Color.GREEN;
        	else if( timeRecs[i+1] <= 2000 )
        		clrs[i] = Color.ORANGE;
        	else
        		clrs[i] = Color.RED;
    		tms[i] = timeRecs[i+1];
    	}
    	
    	// Set values
		barTime1.setValue((int)tms[0]);
		barTime2.setValue((int)tms[1]);
		barTime3.setValue((int)tms[2]);
		barTime4.setValue((int)tms[3]);
		barTime5.setValue((int)tms[4]);
		barTime6.setValue((int)tms[5]);
		barTime7.setValue((int)tms[6]);
    	
		// Set strings
    	barTime1.setString(Long.toString(tms[0]) + " us");
    	barTime2.setString(Long.toString(tms[1]) + " us");
    	barTime3.setString(Long.toString(tms[2]) + " us");
    	barTime4.setString(Long.toString(tms[3]) + " us");
    	barTime5.setString(Long.toString(tms[4]) + " us");
    	barTime6.setString(Long.toString(tms[5]) + " us");
    	barTime7.setString(Long.toString(tms[6]) + " us");
    	
    	// Set colors
    	barTime1.setForeground(clrs[0]);
    	barTime2.setForeground(clrs[1]);
    	barTime3.setForeground(clrs[2]);
    	barTime4.setForeground(clrs[3]);
    	barTime5.setForeground(clrs[4]);
    	barTime6.setForeground(clrs[5]);
    	barTime7.setForeground(clrs[6]);
    }
    
    
    //*********************************************************************//
    //******************** Angles/Gyro Data Functions *********************//
    //*********************************************************************//
    
    
    /*
     * Updates angles (YPR) data
     * 
     * @param ypr Array containing Yaw, Pitch and Roll
     */
    public void setYPR(short[] ypr){
    	// Initial assert
    	if( ypr.length != 3 )
    		return;
    	
    	// Set values on bars
    	barYaw.setValue(ypr[0]);
    	barPitch.setValue(ypr[1]);
    	barRoll.setValue(ypr[2]);
    	
    	// Set strings on bars
    	NumberFormat formatter = new DecimalFormat("#0.00");
    	barYaw.setString(formatter.format(((double)ypr[0])/100) + " °");
    	barPitch.setString(formatter.format(((double)ypr[1])/100) + " °");
    	barRoll.setString(formatter.format(((double)ypr[2])/100) + " °");
    }
    
    
    /*
     * Updates gyro (XYZ) data
     * 
     * @param xyz Array containing gyro X, Y and Z axes
     */
    public void setGyroXYZ(short[] xyz){
    	// Initial assert
    	if( xyz.length != 3 )
    		return;
    	
    	barGyroX.setValue(xyz[0]);
    	barGyroY.setValue(xyz[1]);
    	barGyroZ.setValue(xyz[2]);
    	
    	// Set strings on bars
    	NumberFormat formatter = new DecimalFormat("#0.00");
    	barGyroX.setString(formatter.format(((double)xyz[0])/100) + " dps");
    	barGyroY.setString(formatter.format(((double)xyz[1])/100) + " dps");
    	barGyroZ.setString(formatter.format(((double)xyz[2])/100) + " dps");
    }
    
        
    //***************************************************************//
    //******************** InOut Data Functions *********************//
    //***************************************************************//
    

    /*
     * Prints input data
     * 
     * @param data Data that has been received
     */
    public void printInputData(int data){
    	if( !dataCaptionOn ) return;
    	
    	InOutDataLock.lock();
    	
    	String d;
    	if( data < 0 )
    		d = "--\n";
    	else if( rdbtnHexData.isSelected() ){
    		d = "0x" + String.format("%02X", data) + "\n";
    		printOutputData(-1);
    	}else{
    		d = "0b" + String.format("%8s", Integer.toBinaryString(data)).replace(' ', '0') + "\n";
    		printOutputData(-1);
    	}
    	
    	try {
			textAreaInputData.getDocument().insertString(0, d, null);
			int nLines = textAreaInputData.getLineCount();
			if( nLines > InputOutputData_nLines ){
				if( rdbtnHexData.isSelected() )
					textAreaInputData.replaceRange("", textAreaInputData.getText().lastIndexOf("0x"), textAreaInputData.getDocument().getLength());
				else
					textAreaInputData.replaceRange("", textAreaInputData.getText().lastIndexOf("0b"), textAreaInputData.getDocument().getLength());
			}
		} catch (BadLocationException e) {
			e.printStackTrace();
		} catch (IllegalArgumentException e){
			System.out.println("Last Index: " + textAreaInputData.getText().lastIndexOf("0x"));
			System.out.println("Length: " + textAreaInputData.getDocument().getLength());
		}
    	
    	InOutDataLock.unlock();
    }
    
    
    /*
     * Prints output data
     * 
     * @param data Data that has been sent
     */
    public void printOutputData(int data){
    	if( !dataCaptionOn ) return;
    	
    	InOutDataLock.lock();
    	
    	String d;
    	if( data < 0 )
    		d = "--\n";
    	else if( rdbtnHexData.isSelected() ){
    		d = "0x" + String.format("%02X", data) + "\n";
			printInputData(-1);
		}
    	else{
    		d = "0b" + String.format("%8s", Integer.toBinaryString(data)).replace(' ', '0') + "\n";
			printInputData(-1);
		}
    	
    	try {
			textAreaOutputData.getDocument().insertString(0, d, null);
			int nLines = textAreaOutputData.getLineCount();
			if( nLines > InputOutputData_nLines ){
				if( rdbtnHexData.isSelected() )
					textAreaOutputData.replaceRange("", textAreaOutputData.getText().lastIndexOf("0x"), textAreaOutputData.getDocument().getLength());
				else
					textAreaOutputData.replaceRange("", textAreaOutputData.getText().lastIndexOf("0b"), textAreaOutputData.getDocument().getLength());
			}
		} catch (BadLocationException e) {
			e.printStackTrace();
		} catch (IllegalArgumentException e){
			System.out.println("Last Index: " + textAreaOutputData.getDocument().getLength());
		}
    	
    	InOutDataLock.unlock();
    }

    
    //******************************************************************//
    //******************** Connect panel Functions *********************//
    //******************************************************************//
    
    
    /*
     * Get currently selected port
     * 
     * @return The selected port
     */
    public String getCOMPort(){
    	return boxCOMPort.getSelectedItem().toString();
    }
    
    
    /*
     * Get currently selected port for controller
     * 
     * @return The selected controller port
     */
    public String getControllerCOMPort(){
    	return boxControllerCOMPort.getSelectedItem().toString();
    }
    
    
    /*
     * Add a new port to the COM ComboBox
     * 
     * @return The selected port
     */
    public void addCOMPort(String com){
    	if( boxCOMModel.getIndexOf(com) == -1 )
    		boxCOMModel.addElement(com);
    }
    
    
    /*
     * Add a new port to the COM ComboBox
     * 
     * @return The selected port
     */
    public void addControllerCOMPort(String com){
    	if( boxControllerCOMModel.getIndexOf(com) == -1 )
    		boxControllerCOMModel.addElement(com);
    }
}